import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import panda from '../assets/images/panda.webp';
import Nav from '../components/Nav'

export default function Home() {
  return (
    <div className='w-full h-screen p-8'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-full'>
        <Nav/>
        <div className='flex p-8 w-full h-5/6 flex-col flex-col-reverse sm:flex-row'>
          <div className={`${styles.div2} opacity-0 w-full h-2/4 flex justify-evenly flex-col sm:h-full sm:w-2/4`}>
            <h1 className='sm: text-2xl md:text-4xl lg:text-5xl w-4/5'>Be a better developer read good articles</h1>
            <h1 className='sm: text-1xl md:text-3xl lg:text-4xl w-4/5 text-neutral-400'>Find all my writings here</h1>
          </div>
          <div className={`${styles.div1} opacity-0 w-full h-2/4 flex justify-evenly items-center sm:h-full sm:w-2/4`}>
            <Image className='w-3/5' src={panda} alt="panda"/>
          </div>
        </div>
      </main>
    </div>
  )
}
